apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipping-service
  name: shipping-service
  namespace: submission3
spec:
  type: NodePort  # Mengubah tipe layanan menjadi NodePort
  ports:
  - port: 91
    targetPort: 3001
  selector:
    app: shipping-service