apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: submission3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/yahyakhaliman/order-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AMQP_URL
          value: "amqp://localhost:5672"
