apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: submission3
spec:
  type: NodePort  # Mengubah tipe layanan menjadi NodePort
  ports:
  - port: 90
    targetPort: 3000
  selector:
    app: order-service