apiVersion: v1
kind: Service # menentukan jenis objek yang akan didefinisikan
metadata: # mendefinisikan metadata terkait objek
  labels:
    app: order-service
  name: order-service
  namespace: submission3
spec:  # memberikan spesifikasi untuk layanan
  type: NodePort   # Mengubah tipe layanan menjadi NodePort supaya dapat diakses melalui port di node
  ports:
  - port: 90
    targetPort: 3000
  selector: # Menentukan selektor yang akan digunakan untuk menemukan pod yang terkait
    app: order-service